name: pce
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - hydra-core==1.3.2
  - pytorch-lightning==1.9.5
  - opencv-python==4.10.0.84
  - ipdb==0.13.13
  - matplotlib==3.5.3
  - scikit-image==0.19.3
  - kornia==0.6.12
  - wandb==0.17.7
  - thop==0.1.1.post2209072238
