name: pce
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - hydra-core=1.1.1
  - pytorch_lightning=1.7.6
  - ipdb=0.13.9
  - opencv-python=4.5.5.64
  - matplotlib=3.5.1
  - scikit-image=0.19.3
  - kornia=0.6.7
  - wandb=0.13.8
  - thop=0.1.1.post2209072238

  - pip:
    - gaussian-splatting/submodules/diff-gaussian-rasterization
    - gaussian-splatting/submodules/simple-knn
